__title__ = "Quart-Login-Extended"
__description__ = "User session management for Quart"
__url__ = "https://github.com/colinochieng/quart-login"
__version_info__ = ("0", "6", "2")
__version__ = ".".join(__version_info__)
__author__ = "Matteo Porta"
__author_email__ = "leafstormrush@gmail.com"
__maintainer__ = "Colin Ochieng"
__license__ = "MIT"
__copyright__ = "(c) 2022 by Matteo Porta, (c) 2026 by Colin Ochieng"
